import {
  Megaphone,
  Table2,
  Workflow,
  Headset,
  PhoneCall,
  Share2,
  CalendarClock,
  BarChart3,
  Search,
  MessageSquare,
  Mail,
  Globe,
  type LucideIcon,
} from "lucide-react";

/* ============================================================
   Service Detail Data
   ------------------------------------------------------------
   Each service has genuine, useful content for a dedicated
   detail page. No thin pages — each has overview, what's
   included, benefits, process, and a FAQ.
   ============================================================ */

export type ServiceDetail = {
  slug: string;
  title: string;
  shortTitle: string;
  icon: LucideIcon;
  color: "electric" | "violet" | "cyan";
  tagline: string;
  metaTitle: string;
  metaDescription: string;
  overview: string[];
  whatsIncluded: string[];
  benefits: { title: string; desc: string }[];
  process: { step: string; title: string; desc: string }[];
  faqs: { q: string; a: string }[];
  relatedServices: string[];
};

export const SERVICE_DETAILS: ServiceDetail[] = [
  {
    slug: "marketing-consulting",
    title: "Marketing Consulting for Real Estate Professionals",
    shortTitle: "Marketing Consulting",
    icon: Megaphone,
    color: "electric",
    tagline: "Campaign planning, growth strategy, and brand positioning tailored to your market.",
    metaTitle: "Real Estate Marketing Consulting | Opus Global Solution",
    metaDescription: "Strategic marketing consulting for US real estate agents. Campaign planning, growth strategy, brand positioning, and market analysis tailored to your local market.",
    overview: [
      "Our marketing consulting service helps licensed real estate agents and brokerages develop clear, actionable growth strategies. We analyze your current marketing efforts, identify gaps, and build a roadmap that aligns with your business goals and local market conditions.",
      "Unlike generic marketing agencies, we specialize exclusively in real estate. We understand the nuances of seller leads, buyer pipelines, MLS integrations, referral networks, and the compliance requirements that govern real estate outreach in the United States.",
      "Every consulting engagement starts with a deep dive into your business: your target counties, your current conversion rates, your team's capacity, and your growth targets. From there, we build a customized marketing plan that you can execute with our support or independently.",
    ],
    whatsIncluded: [
      "Comprehensive marketing audit of your current efforts",
      "Custom growth strategy with quarterly milestones",
      "Local market analysis and competitive positioning",
      "Campaign planning across channels (outreach, digital, email, SMS)",
      "Brand positioning and messaging guidance",
      "KPI tracking framework with monthly performance reviews",
      "Recommendations for CRM optimization and pipeline hygiene",
      "Compliance review of existing outreach practices",
    ],
    benefits: [
      { title: "Clarity", desc: "Know exactly what to do next, in what order, and why — no more guessing." },
      { title: "Local focus", desc: "Strategies built around your specific counties and target seller demographics." },
      { title: "Compliance-first", desc: "Every recommendation respects TCPA, DNC, CAN-SPAM, and Fair Housing regulations." },
      { title: "Measurable results", desc: "Clear KPIs and monthly reviews so you can track ROI on every initiative." },
    ],
    process: [
      { step: "1", title: "Discovery Call", desc: "We learn about your business, goals, market, and current challenges." },
      { step: "2", title: "Marketing Audit", desc: "We review your existing campaigns, CRM, outreach, and digital presence." },
      { step: "3", title: "Strategy Development", desc: "We build a customized marketing plan with prioritized initiatives." },
      { step: "4", title: "Implementation Support", desc: "We help you execute the plan through our service packages or your own team." },
    ],
    faqs: [
      { q: "Do I need marketing consulting if I already have a CRM?", a: "A CRM is a tool. Consulting helps you use it strategically — defining your lead sources, follow-up cadence, pipeline stages, and reporting so the CRM actually drives growth rather than just storing data." },
      { q: "Can you help with a specific market or county?", a: "Yes. Our consulting is tailored to your target counties. We analyze local seller demographics, competition, and market conditions to build a strategy that works in your specific area." },
      { q: "Is the consulting a one-time engagement or ongoing?", a: "It can be either. Most clients start with a one-time strategy engagement, then continue with monthly performance reviews through our service packages. We adjust the strategy based on real results." },
    ],
    relatedServices: ["crm-support", "real-estate-outreach", "digital-advertising"],
  },
  {
    slug: "real-estate-outreach",
    title: "Real Estate Outreach Support",
    shortTitle: "Outreach Support",
    icon: PhoneCall,
    color: "violet",
    tagline: "Human-based, verified communication with documented follow-up processes.",
    metaTitle: "Real Estate Outreach Support Services | Opus Global Solution",
    metaDescription: "Human-verified outreach support for real estate agents. Consent-based communication, documented follow-ups, CRM logging, and TCPA-compliant prospecting.",
    overview: [
      "Our outreach support service handles prospect communication for real estate professionals using human-only, consent-based methods. We never use autodialers, robocalls, or automated SMS blasts. Every contact is made by a trained professional who documents the interaction in your CRM.",
      "This service is designed for agents who want to expand their pipeline without spending hours on the phone or risking compliance violations. We manage the entire outreach lifecycle: identifying contacts, making initial connections, following up, qualifying interest, and booking appointments.",
      "Every outreach campaign is documented end-to-end. You receive records of who was contacted, when, what was discussed, and what the next step is. This transparency protects you legally and gives you a clear picture of your pipeline health.",
    ],
    whatsIncluded: [
      "Human-only prospect calling (no autodialers or robocalls)",
      "Consent-based outreach across all channels",
      "Documented follow-up sequences with CRM logging",
      "Lead qualification and appointment booking",
      "TCPA, DNC, CAN-SPAM, and CCPA/CPRA compliant processes",
      "Outreach performance reporting with contact metrics",
      "Custom call scripts tailored to your market and services",
      "Reconnection campaigns for past clients and expired leads",
    ],
    benefits: [
      { title: "Compliance protection", desc: "Every contact is consent-based and documented, protecting you from regulatory risk." },
      { title: "Time recovery", desc: "Reclaim 15+ hours per week that you'd otherwise spend on phone calls and follow-ups." },
      { title: "Quality over quantity", desc: "Human conversations qualify leads better than any automated system." },
      { title: "Full transparency", desc: "Every interaction is logged in your CRM with timestamps and notes." },
    ],
    process: [
      { step: "1", title: "Campaign Setup", desc: "We define your target market, contact criteria, and outreach cadence." },
      { step: "2", title: "Script Development", desc: "We create call scripts and messaging frameworks tailored to your services." },
      { step: "3", title: "Outreach Execution", desc: "Our team makes consent-based contacts, documents results, and logs everything in your CRM." },
      { step: "4", title: "Reporting & Optimization", desc: "Weekly performance reports with recommendations for script and targeting improvements." },
    ],
    faqs: [
      { q: "Do you use autodialers or robocalls?", a: "No. We use human-only outreach. Every call is made by a trained professional. We do not use autodialers, robocalls, or pre-recorded messages under any circumstances." },
      { q: "How do you ensure DNC compliance?", a: "We scrub every contact list against the National Do Not Call Registry before any outreach begins. We also maintain internal suppression lists and document consent for every contact." },
      { q: "Can you work with my existing CRM?", a: "Yes. We integrate with most major real estate CRMs. If you don't have one, we can set one up for you as part of our CRM Support service." },
      { q: "What areas do you cover?", a: "We serve licensed real estate professionals across the United States. Our outreach campaigns are tailored to your specific target counties and markets." },
    ],
    relatedServices: ["marketing-consulting", "crm-support", "sms-campaign-support"],
  },
  {
    slug: "crm-support",
    title: "CRM Support for Real Estate Professionals",
    shortTitle: "CRM Support",
    icon: Table2,
    color: "cyan",
    tagline: "CRM setup, lead organization, pipeline optimization, and automation.",
    metaTitle: "Real Estate CRM Support & Setup | Opus Global Solution",
    metaDescription: "Professional CRM support for real estate agents. CRM setup, lead organization, pipeline optimization, automation, and reporting for US real estate professionals.",
    overview: [
      "A CRM is only as good as the way it's configured and used. Our CRM support service helps real estate professionals set up, optimize, and maintain their customer relationship management system so it actually drives deals forward instead of just storing contacts.",
      "We work with the major real estate CRM platforms and can help you migrate from spreadsheets or legacy systems to a proper CRM. Our team handles the setup, customizes pipeline stages, configures automation rules, and trains your team on best practices.",
      "Beyond initial setup, we provide ongoing CRM management: data hygiene, lead assignment, follow-up scheduling, pipeline reporting, and automation adjustments. Your CRM stays clean, current, and actionable.",
    ],
    whatsIncluded: [
      "CRM platform selection guidance and setup",
      "Custom pipeline stage configuration for real estate workflows",
      "Lead capture form integration with your website",
      "Automated follow-up sequences and reminder setup",
      "Data migration from spreadsheets or legacy systems",
      "Pipeline hygiene: deduplication, data enrichment, cleanup",
      "Custom dashboard and reporting configuration",
      "Team training on CRM best practices",
    ],
    benefits: [
      { title: "No more lost leads", desc: "Every lead is captured, assigned, and followed up on automatically." },
      { title: "Clean data", desc: "Deduplicated, enriched, and standardized records that you can actually use." },
      { title: "Automation", desc: "Follow-ups, reminders, and notifications happen without manual intervention." },
      { title: "Visibility", desc: "Custom dashboards show your pipeline health at a glance." },
    ],
    process: [
      { step: "1", title: "Assessment", desc: "We review your current system (or lack thereof) and define your CRM requirements." },
      { step: "2", title: "Setup & Migration", desc: "We configure the CRM, migrate your data, and set up automation rules." },
      { step: "3", title: "Training", desc: "We train your team on how to use the CRM effectively day-to-day." },
      { step: "4", title: "Ongoing Management", desc: "We maintain data hygiene, adjust automation, and provide monthly pipeline reports." },
    ],
    faqs: [
      { q: "Which CRM platforms do you support?", a: "We work with most major real estate CRM platforms including Follow Up Boss, KVCore, LionDesk, Top Producer, HubSpot, and others. If you're not sure which to choose, we'll recommend based on your team size and workflow." },
      { q: "Can you migrate data from my spreadsheet?", a: "Yes. We handle data migration from Google Sheets, Excel, and other formats. We clean, deduplicate, and standardize the data during migration so your CRM starts with quality records." },
      { q: "Do you provide ongoing CRM management?", a: "Yes. Our service packages include ongoing CRM management: data hygiene, automation adjustments, pipeline reporting, and support. You don't have to manage the CRM yourself." },
      { q: "How long does CRM setup take?", a: "A basic setup takes 1-2 weeks. A full migration with custom automation, team training, and reporting setup takes 3-4 weeks depending on data volume and complexity." },
    ],
    relatedServices: ["marketing-consulting", "real-estate-outreach", "workflow-automation"],
  },
  {
    slug: "workflow-automation",
    title: "Workflow Automation for Real Estate",
    shortTitle: "Workflow Automation",
    icon: Workflow,
    color: "electric",
    tagline: "Automate repetitive tasks, lead tracking, reminders, and follow-ups.",
    metaTitle: "Real Estate Workflow Automation | Opus Global Solution",
    metaDescription: "Workflow automation for real estate agents. Automate lead tracking, follow-ups, reminders, task assignments, and pipeline management to save hours every week.",
    overview: [
      "Workflow automation eliminates the repetitive manual tasks that eat up your day. Instead of manually sending follow-up emails, setting reminders, updating pipeline stages, and assigning tasks, your systems handle it automatically based on triggers you define.",
      "We build automation workflows specifically for real estate processes: new lead intake, follow-up sequences, appointment scheduling, listing status updates, closing checklists, and post-closing nurture campaigns.",
      "Every workflow is documented, tested, and monitored. When a step fails or a process changes, we adjust the automation so your business keeps running smoothly without manual intervention.",
    ],
    whatsIncluded: [
      "Automated lead intake and assignment workflows",
      "Follow-up email and SMS sequences triggered by pipeline stage",
      "Automated appointment reminders and confirmations",
      "Task assignment rules based on lead status or territory",
      "Listing update notifications and sync workflows",
      "Closing checklist automation with milestone tracking",
      "Post-closing nurture and referral request sequences",
      "Pipeline stage automation with conditional logic",
    ],
    benefits: [
      { title: "Save 10+ hours/week", desc: "Eliminate manual follow-ups, reminders, and status updates from your daily routine." },
      { title: "No missed follow-ups", desc: "Every lead gets contacted on schedule, every time, without you remembering." },
      { title: "Consistency", desc: "Every client gets the same high-quality experience regardless of how busy you are." },
      { title: "Scalability", desc: "Handle 3x more leads without adding headcount or working longer hours." },
    ],
    process: [
      { step: "1", title: "Process Mapping", desc: "We document your current workflows and identify automation opportunities." },
      { step: "2", title: "Workflow Design", desc: "We design automation sequences with triggers, conditions, and actions." },
      { step: "3", title: "Implementation", desc: "We build and test the workflows in your CRM and connected tools." },
      { step: "4", title: "Monitoring", desc: "We monitor performance, fix failures, and optimize sequences over time." },
    ],
    faqs: [
      { q: "What tools do you use for automation?", a: "We work with your existing CRM's automation features plus integration tools like Zapier, Make (Integromat), and native platform automations. We choose the simplest reliable approach." },
      { q: "Can automation replace my assistant?", a: "Automation handles repetitive tasks, but it can't replace human judgment in conversations, negotiations, and relationship-building. Many clients use automation alongside our Virtual Assistant service for maximum efficiency." },
      { q: "What happens if an automation fails?", a: "We monitor all workflows and receive alerts when failures occur. We fix issues promptly and add fallback notifications so you're always informed if a step doesn't execute." },
    ],
    relatedServices: ["crm-support", "marketing-consulting", "email-campaign-support"],
  },
  {
    slug: "virtual-assistance",
    title: "Virtual Assistant Services for Real Estate",
    shortTitle: "Virtual Assistance",
    icon: Headset,
    color: "violet",
    tagline: "Administrative support, scheduling, data organization, and client communication.",
    metaTitle: "Real Estate Virtual Assistant Services | Opus Global Solution",
    metaDescription: "Dedicated virtual assistants for real estate professionals. Customer support, prospect calling, calendar management, CRM management, social media, and website management.",
    overview: [
      "Our virtual assistant service provides dedicated, trained professionals who handle the administrative workload that keeps real estate agents from focusing on closing deals. From managing your calendar to updating your CRM, our VAs become an extension of your team.",
      "Each virtual assistant is assigned to you based on your specific needs and market. They learn your processes, your preferred tools, and your communication style. You work with the same VA every day — not a rotating call center.",
      "Virtual assistants can handle a wide range of tasks: inbound customer support, prospect calling, calendar management, CRM data entry, social media posting, website updates, email management, document preparation, and more. You choose what to delegate.",
    ],
    whatsIncluded: [
      "Dedicated virtual assistant matched to your business",
      "Inbound customer support and inquiry handling",
      "Outbound prospect calling with documented results",
      "Calendar management and appointment scheduling",
      "CRM data entry, updates, and pipeline maintenance",
      "Social media content scheduling and posting",
      "Website updates: listings, landing pages, blog posts",
      "Email and SMS management on your behalf",
    ],
    benefits: [
      { title: "Dedicated VA", desc: "Work with the same assistant every day who knows your business inside out." },
      { title: "Flexible hours", desc: "Up to 40 hours per month with the ability to scale up as you grow." },
      { title: "Real estate trained", desc: "Our VAs understand real estate terminology, processes, and compliance." },
      { title: "Full reporting", desc: "Daily or weekly task reports so you always know what was accomplished." },
    ],
    process: [
      { step: "1", title: "Needs Assessment", desc: "We identify which tasks to delegate and what skills your VA needs." },
      { step: "2", title: "VA Matching", desc: "We match you with a dedicated VA trained in real estate support." },
      { step: "3", title: "Onboarding", desc: "Your VA learns your tools, processes, and communication preferences." },
      { step: "4", title: "Ongoing Support", desc: "Your VA handles delegated tasks daily with regular performance reviews." },
    ],
    faqs: [
      { q: "Will I work with the same VA every day?", a: "Yes. You are assigned a dedicated virtual assistant who works with you consistently. This ensures they learn your business, preferences, and processes over time." },
      { q: "What hours does my VA work?", a: "VAs work during US business hours (EST). Plans range from 10 to 40 hours per month. If you need more coverage, we can scale up your plan." },
      { q: "Can my VA make calls on my behalf?", a: "Yes. Our VAs are trained in consent-based, compliant outreach. They can make prospect calls, follow up with leads, and handle inbound inquiries — all documented in your CRM." },
      { q: "What tools does my VA use?", a: "Your VA uses whatever tools you already use: your CRM, calendar, email, social media platforms, and website CMS. We adapt to your workflow, not the other way around." },
    ],
    relatedServices: ["crm-support", "real-estate-outreach", "calendar-management"],
  },
  {
    slug: "seo-online-presence",
    title: "SEO & Online Presence for Real Estate",
    shortTitle: "SEO & Online Presence",
    icon: Search,
    color: "cyan",
    tagline: "Boost your visibility through search optimization and relevant, high-quality content strategies.",
    metaTitle: "Real Estate SEO Services & Online Presence | Opus Global Solution",
    metaDescription: "SEO and online presence services for real estate agents. Search optimization, content strategy, Google Business Profile, and local visibility for US real estate professionals.",
    overview: [
      "Being found online is critical for real estate professionals. Our SEO and online presence service helps you rank higher in search results, optimize your Google Business Profile, and build a content strategy that attracts motivated sellers in your target markets.",
      "We focus on practical, results-driven SEO — not vanity metrics. That means optimizing for the searches that actually drive business: 'sell my house [city]', 'real estate agent [neighborhood]', and local intent queries that indicate a seller is ready to act.",
      "Our approach includes on-page optimization, Google Business Profile management, local citation building, content planning, and performance tracking. We help you build a sustainable online presence that compounds over time.",
    ],
    whatsIncluded: [
      "Website SEO audit with prioritized action items",
      "On-page optimization: titles, meta tags, headings, content",
      "Google Business Profile setup and optimization",
      "Local citation management across directories",
      "Keyword research for your target markets and counties",
      "Content strategy with topic clusters for real estate",
      "Monthly SEO performance reports with ranking tracking",
      "Technical SEO: site speed, mobile, structured data",
    ],
    benefits: [
      { title: "More inbound leads", desc: "Rank for searches that motivated sellers actually make in your market." },
      { title: "Local dominance", desc: "Appear in Google Maps and local results for your target counties." },
      { title: "Long-term asset", desc: "SEO compounds over time — every piece of optimized content works for you 24/7." },
      { title: "Measurable ROI", desc: "Track exactly which keywords and pages drive traffic, leads, and closings." },
    ],
    process: [
      { step: "1", title: "SEO Audit", desc: "We audit your website, Google Business Profile, and local citations." },
      { step: "2", title: "Keyword Research", desc: "We identify high-intent keywords for your target markets and counties." },
      { step: "3", title: "Optimization", desc: "We implement on-page, technical, and local SEO improvements." },
      { step: "4", title: "Content & Tracking", desc: "We build a content calendar and track rankings, traffic, and leads monthly." },
    ],
    faqs: [
      { q: "How long does SEO take to show results?", a: "SEO is a long-term strategy. You'll typically see initial improvements in 2-3 months, with meaningful traffic growth in 4-6 months. Local SEO (Google Maps) can show results faster — often within 4-8 weeks." },
      { q: "Do you guarantee first-page rankings?", a: "No legitimate SEO provider guarantees specific rankings. We guarantee transparent, white-hat practices, regular reporting, and continuous optimization. Results depend on your market, competition, and consistency." },
      { q: "Can you help with my Google Business Profile?", a: "Yes. We set up, optimize, and manage your Google Business Profile including posts, reviews, photos, and Q&A — all critical for local search visibility." },
    ],
    relatedServices: ["marketing-consulting", "digital-advertising", "website-management"],
  },
  {
    slug: "digital-advertising",
    title: "Digital Advertising Management for Real Estate",
    shortTitle: "Digital Advertising",
    icon: Share2,
    color: "electric",
    tagline: "Compliant campaigns across Google and social media to increase visibility and reach motivated sellers.",
    metaTitle: "Real Estate Digital Advertising Management | Opus Global Solution",
    metaDescription: "Digital advertising management for real estate agents. Google Ads, Facebook Ads, and social media campaigns to reach motivated sellers. Compliance-first approach.",
    overview: [
      "Our digital advertising service manages paid campaigns across Google, Facebook, Instagram, and other platforms to put your message in front of motivated sellers in your target markets. We handle campaign setup, targeting, creative, optimization, and reporting.",
      "Every campaign is built with compliance in mind. We ensure ad copy respects Fair Housing guidelines, landing pages include required disclosures, and targeting doesn't violate platform policies or housing discrimination laws.",
      "We focus on ROI, not impressions. Every dollar spent is tracked from click to lead to closing, so you know exactly which campaigns and channels are profitable.",
    ],
    whatsIncluded: [
      "Google Ads campaign setup and management",
      "Facebook and Instagram Ads campaign management",
      "Landing page creation and optimization",
      "Ad creative: copywriting, design guidance, and A/B testing",
      "Audience targeting based on seller intent signals",
      "Conversion tracking from click to lead to closing",
      "Fair Housing compliant ad copy and creative review",
      "Monthly performance reports with cost-per-lead analysis",
    ],
    benefits: [
      { title: "Targeted reach", desc: "Put your message in front of people actively searching to sell or researching agents." },
      { title: "Compliance protection", desc: "Every ad and landing page reviewed for Fair Housing and platform compliance." },
      { title: "Transparent ROI", desc: "Track every dollar from ad spend to closed transaction." },
      { title: "Fast results", desc: "Unlike SEO, paid ads can generate leads within days of launch." },
    ],
    process: [
      { step: "1", title: "Strategy & Targeting", desc: "We define your target audience, budget, and campaign objectives." },
      { step: "2", title: "Creative & Setup", desc: "We create ad copy, design landing pages, and configure tracking." },
      { step: "3", title: "Launch & Optimize", desc: "We launch campaigns, monitor performance, and optimize daily." },
      { step: "4", title: "Report & Scale", desc: "Monthly reports with recommendations to scale what works and cut what doesn't." },
    ],
    faqs: [
      { q: "What's the minimum ad budget I need?", a: "We recommend a minimum of $500/month in ad spend for a single market. This allows enough data collection to optimize campaigns effectively. Larger markets or multiple counties require higher budgets." },
      { q: "Do you handle the ad creative?", a: "Yes. We write ad copy, provide design guidance, and create landing pages. For real estate-specific imagery, we can work with your listings or recommend stock photography." },
      { q: "Are the ads Fair Housing compliant?", a: "Yes. Every ad is reviewed for Fair Housing Act compliance. We avoid discriminatory targeting, protected class references, and language that could be interpreted as exclusionary." },
    ],
    relatedServices: ["marketing-consulting", "seo-online-presence", "website-management"],
  },
  {
    slug: "social-media-management",
    title: "Social Media Management for Real Estate",
    shortTitle: "Social Media Management",
    icon: Share2,
    color: "violet",
    tagline: "Consistent, on-brand content across your channels to keep you top-of-mind with sellers and buyers.",
    metaTitle: "Real Estate Social Media Management | Opus Global Solution",
    metaDescription: "Social media management for real estate agents. Content creation, scheduling, posting, and engagement across Facebook, Instagram, and LinkedIn for US real estate professionals.",
    overview: [
      "Consistent social media presence keeps you top-of-mind with past clients, active prospects, and your local community. Our social media management service handles content creation, scheduling, posting, and basic engagement across your channels.",
      "We create real estate-specific content: market updates, listing highlights, community spotlights, agent tips, and seasonal content that resonates with sellers and buyers in your target markets. Every post is on-brand and professional.",
      "Your virtual assistant or dedicated social media manager handles the day-to-day posting, scheduling, and community management so your channels stay active without consuming your time.",
    ],
    whatsIncluded: [
      "Content calendar with 12-20 posts per month",
      "Real estate-specific content: market updates, listings, tips",
      "Post scheduling across Facebook, Instagram, and LinkedIn",
      "Community management: responding to comments and messages",
      "Hashtag strategy for local and real estate reach",
      "Story and reel creation guidance",
      "Monthly performance reports with engagement metrics",
      "Brand-consistent visual style and tone of voice",
    ],
    benefits: [
      { title: "Stay top-of-mind", desc: "Past clients see your name regularly, increasing referral likelihood." },
      { title: "Professional presence", desc: "Consistent, high-quality content builds trust with prospects." },
      { title: "Local authority", desc: "Market updates and community content position you as the local expert." },
      { title: "No time required", desc: "Your VA handles everything — you approve content and move on." },
    ],
    process: [
      { step: "1", title: "Brand Audit", desc: "We review your current social presence and define your brand voice." },
      { step: "2", title: "Content Planning", desc: "We build a monthly content calendar with post types and topics." },
      { step: "3", title: "Creation & Scheduling", desc: "We create posts, schedule them, and manage engagement." },
      { step: "4", title: "Reporting", desc: "Monthly reports on reach, engagement, and follower growth." },
    ],
    faqs: [
      { q: "Which platforms do you manage?", a: "We manage Facebook, Instagram, and LinkedIn by default. We can also support Twitter/X and Pinterest if relevant to your market. We don't manage TikTok at this time." },
      { q: "Do you create the content or do I?", a: "We create all content: copy, graphics, and scheduling. You review and approve the monthly calendar in advance. For listing-specific posts, we work with your photos and property details." },
      { q: "How often do you post?", a: "Standard plans include 12-20 posts per month (3-5 per week). We can scale up for active markets or down for smaller territories. Consistency matters more than volume." },
    ],
    relatedServices: ["virtual-assistance", "digital-advertising", "website-management"],
  },
  {
    slug: "email-campaign-support",
    title: "Email Campaign Support for Real Estate",
    shortTitle: "Email Campaign Support",
    icon: Mail,
    color: "cyan",
    tagline: "Opt-in only email campaigns with compliance features, automated drips, and delivery analytics.",
    metaTitle: "Real Estate Email Campaign Support | Opus Global Solution",
    metaDescription: "Email campaign support for real estate agents. Opt-in campaigns, automated drips, newsletter management, and delivery analytics. CAN-SPAM compliant.",
    overview: [
      "Email remains one of the highest-ROI channels for real estate professionals. Our email campaign support service manages opt-in email marketing: newsletters, drip campaigns, market updates, and nurture sequences that keep your pipeline warm.",
      "Every campaign is CAN-SPAM compliant with proper opt-in management, unsubscribe handling, and physical address inclusion. We never send to purchased lists — only to contacts who have given explicit consent.",
      "We handle the full lifecycle: content creation, template design, list segmentation, scheduling, A/B testing, and performance reporting. You see open rates, click rates, and lead attribution for every campaign.",
    ],
    whatsIncluded: [
      "Email campaign strategy and content calendar",
      "Newsletter design and content creation",
      "Automated drip sequences for new leads and nurture",
      "Market update emails with local data",
      "List segmentation by lead source, status, and interest",
      "A/B testing of subject lines and content",
      "CAN-SPAM compliance: opt-in, unsubscribe, physical address",
      "Monthly performance reports: open rate, CTR, conversions",
    ],
    benefits: [
      { title: "Warm pipeline", desc: "Automated nurture sequences keep leads engaged until they're ready to act." },
      { title: "Compliance built-in", desc: "Every campaign is CAN-SPAM compliant with proper consent and unsubscribe." },
      { title: "Reusable content", desc: "Drip sequences work 24/7 — write once, nurture forever." },
      { title: "Attribution", desc: "Know exactly which emails drove leads, appointments, and closings." },
    ],
    process: [
      { step: "1", title: "Strategy", desc: "We define your email segments, campaign types, and frequency." },
      { step: "2", title: "Setup", desc: "We configure your email platform, templates, and automation rules." },
      { step: "3", title: "Content Creation", desc: "We write and design newsletters, drip sequences, and market updates." },
      { step: "4", title: "Send & Report", desc: "We schedule campaigns, monitor delivery, and report monthly." },
    ],
    faqs: [
      { q: "Do you use purchased email lists?", a: "No. We only send to contacts who have given explicit opt-in consent. Purchased lists are non-compliant, damage your sender reputation, and produce terrible results. We help you build your list organically." },
      { q: "What email platforms do you support?", a: "We work with Mailchimp, Constant Contact, KVCore, Follow Up Boss, HubSpot, and most major email platforms. We can also set up a new platform if you don't have one." },
      { q: "How often should I send emails?", a: "For a nurture sequence, emails are triggered by lead actions (no fixed schedule). For newsletters, we recommend bi-weekly or monthly. Market updates can go weekly during active seasons. We'll recommend based on your audience." },
    ],
    relatedServices: ["marketing-consulting", "sms-campaign-support", "workflow-automation"],
  },
  {
    slug: "sms-campaign-support",
    title: "SMS Campaign Support for Real Estate",
    shortTitle: "SMS Campaign Support",
    icon: MessageSquare,
    color: "electric",
    tagline: "Opt-in only communications with full compliance features including STOP/HELP and unsubscribe.",
    metaTitle: "Real Estate SMS Campaign Support | Opus Global Solution",
    metaDescription: "SMS campaign support for real estate agents. Opt-in text messaging with TCPA compliance, STOP/HELP keywords, and delivery tracking for US real estate professionals.",
    overview: [
      "SMS has one of the highest open rates of any communication channel — but it's also the most heavily regulated. Our SMS campaign support service manages opt-in text messaging campaigns that are fully TCPA compliant, with proper consent documentation, STOP/HELP keyword handling, and unsubscribe management.",
      "We help you use SMS strategically: appointment reminders, follow-up nudges, market alerts, and nurture touches that complement (not replace) your email and phone outreach. Every message is logged, consented, and compliant.",
      "We handle the technical setup: short code or long code provisioning, keyword configuration, opt-in flow design, message scheduling, and compliance documentation. You send messages with confidence.",
    ],
    whatsIncluded: [
      "SMS campaign strategy and message calendar",
      "TCPA-compliant opt-in flow design and documentation",
      "STOP, HELP, and unsubscribe keyword management",
      "Appointment reminder and confirmation texts",
      "Follow-up nurture sequences via SMS",
      "Market alert and new listing notifications",
      "Message scheduling and delivery tracking",
      "Compliance documentation and audit trail",
    ],
    benefits: [
      { title: "98% open rate", desc: "Text messages are opened and read far more than emails — ideal for time-sensitive communication." },
      { title: "Full compliance", desc: "TCPA-compliant opt-in, STOP/HELP keywords, and complete audit trail protect you legally." },
      { title: "Strategic use", desc: "SMS complements your other channels — we don't spam, we use it when it matters most." },
      { title: "Automated", desc: "Reminder and nurture sequences trigger automatically based on lead actions." },
    ],
    process: [
      { step: "1", title: "Compliance Setup", desc: "We configure opt-in flows, keywords, and compliance documentation." },
      { step: "2", title: "Strategy", desc: "We define when SMS is appropriate vs email vs phone for each scenario." },
      { step: "3", title: "Campaign Build", desc: "We create message templates, sequences, and scheduling rules." },
      { step: "4", title: "Monitor & Report", desc: "We track delivery, opt-outs, and engagement monthly." },
    ],
    faqs: [
      { q: "Is SMS marketing legal for real estate?", a: "Yes, if done correctly. SMS marketing is legal under the TCPA when you have prior express written consent from the recipient. We handle the compliance framework so every message is properly consented and documented." },
      { q: "What happens if someone replies STOP?", a: "Our system automatically processes STOP replies, unsubscribes the contact immediately, and logs the opt-out. The contact will never receive another promotional SMS from your campaigns. HELP replies trigger an automated response with support contact information." },
      { q: "Can I send SMS to my past clients?", a: "Only if they have given explicit opt-in consent for SMS communications. Having a phone number on file is not sufficient — we help you obtain and document proper consent before any SMS campaign begins." },
    ],
    relatedServices: ["email-campaign-support", "real-estate-outreach", "workflow-automation"],
  },
  {
    slug: "website-management",
    title: "Website Management for Real Estate",
    shortTitle: "Website Management",
    icon: Globe,
    color: "cyan",
    tagline: "Listing updates, landing pages, and performance tweaks handled, so your web presence always converts.",
    metaTitle: "Real Estate Website Management | Opus Global Solution",
    metaDescription: "Website management for real estate agents. Listing updates, landing pages, performance optimization, and content updates for US real estate professionals.",
    overview: [
      "Your website is your digital storefront. Our website management service keeps it updated, fast, and conversion-focused. We handle listing updates, landing page creation, content publishing, performance monitoring, and technical maintenance.",
      "Whether you have a custom website, a WordPress site, or a templated real estate platform, our team can manage the day-to-day updates that keep it fresh and functional. You focus on clients; we keep the website working.",
      "We also create conversion-optimized landing pages for your marketing campaigns — each designed to capture seller leads with clear calls-to-action, compliance disclosures, and mobile-first design.",
    ],
    whatsIncluded: [
      "Listing updates: add, edit, remove, and sync property listings",
      "Landing page creation for ad campaigns and lead capture",
      "Blog post publishing and formatting",
      "Website performance monitoring (speed, uptime, errors)",
      "Content updates: text changes, image swaps, page additions",
      "SEO on-page optimization (titles, meta, headings, alt text)",
      "Mobile responsiveness checks and fixes",
      "Monthly website health report with recommendations",
    ],
    benefits: [
      { title: "Always current", desc: "Listings, content, and information are updated promptly — no stale pages." },
      { title: "Conversion-focused", desc: "Landing pages designed to capture leads, not just look pretty." },
      { title: "Technical peace of mind", desc: "We monitor performance, fix issues, and keep your site fast and secure." },
      { title: "SEO-friendly", desc: "Every page update includes on-page SEO best practices." },
    ],
    process: [
      { step: "1", title: "Audit", desc: "We review your website's current state, performance, and content gaps." },
      { step: "2", title: "Prioritize", desc: "We identify the most impactful updates: listings, landing pages, SEO." },
      { step: "3", title: "Execute", desc: "We make updates, create pages, and optimize content on a regular schedule." },
      { step: "4", title: "Report", desc: "Monthly health report covering traffic, performance, and conversion metrics." },
    ],
    faqs: [
      { q: "Do you build websites from scratch?", a: "Our primary service is managing and optimizing existing websites. If you need a new website, we can provide recommendations and refer you to a development partner. We focus on keeping your current site updated and performing well." },
      { q: "Can you update my WordPress site?", a: "Yes. We manage WordPress sites including plugin updates, content changes, blog publishing, and performance optimization. We also work with custom CMS platforms and real estate-specific website builders." },
      { q: "How quickly can you create a landing page?", a: "Standard landing pages are delivered within 3-5 business days. Complex pages with custom forms or integrations may take 7-10 business days. Rush delivery is available for active campaigns." },
    ],
    relatedServices: ["seo-online-presence", "social-media-management", "digital-advertising"],
  },
  {
    slug: "calendar-management",
    title: "Calendar Management & Appointment Coordination",
    shortTitle: "Calendar Management",
    icon: CalendarClock,
    color: "violet",
    tagline: "Scheduling, calendar management, and client reminders handled for you.",
    metaTitle: "Real Estate Calendar Management & Appointment Setting | Opus Global Solution",
    metaDescription: "Calendar management and appointment coordination for real estate agents. Scheduling, confirmations, reminders, and client coordination handled by dedicated virtual assistants.",
    overview: [
      "Missed appointments and scheduling conflicts cost real estate professionals deals. Our calendar management service ensures every appointment is scheduled, confirmed, and reminded — so you show up prepared and your clients feel valued.",
      "Your virtual assistant manages your calendar end-to-end: scheduling new appointments, sending confirmation messages, rescheduling conflicts, preparing meeting agendas, and sending follow-up reminders via email and SMS.",
      "We integrate with your existing calendar (Google Calendar, Outlook, Calendly, or your CRM's scheduling tool) so there's no new system to learn. We just make your current calendar work better.",
    ],
    whatsIncluded: [
      "Appointment scheduling and calendar management",
      "Automated confirmation emails and SMS reminders",
      "Rescheduling and conflict resolution",
      "Meeting prep: agenda, documents, and property details",
      "Client follow-up reminders (24hr, 2hr, and post-meeting)",
      "Calendar sync across multiple devices and team members",
      "Daily schedule summary delivered each morning",
      "Weekly calendar review with optimization recommendations",
    ],
    benefits: [
      { title: "No-show reduction", desc: "Automated reminders reduce no-shows by up to 70%." },
      { title: "Always prepared", desc: "Meeting agendas and property details prepared before you walk in." },
      { title: "Conflict-free", desc: "Double-bookings and scheduling gaps eliminated through active management." },
      { title: "Client experience", desc: "Professional scheduling and reminders make clients feel valued and respected." },
    ],
    process: [
      { step: "1", title: "Calendar Audit", desc: "We review your current scheduling process and calendar tools." },
      { step: "2", title: "Setup", desc: "We configure reminders, confirmation flows, and sync rules." },
      { step: "3", title: "Daily Management", desc: "Your VA manages scheduling, confirmations, and reminders daily." },
      { step: "4", title: "Optimization", desc: "Weekly reviews to identify scheduling inefficiencies and improve." },
    ],
    faqs: [
      { q: "Do I need to change my calendar tool?", a: "No. We work with Google Calendar, Outlook, Apple Calendar, Calendly, and most CRM scheduling tools. We adapt to your existing setup." },
      { q: "How do clients book appointments?", a: "Clients can book through your existing scheduling link, by calling your VA directly, or by emailing. We manage all channels and confirm every appointment." },
      { q: "What happens if a client cancels?", a: "Your VA handles cancellations professionally, offers alternative times, and updates your calendar immediately. We also trigger a re-engagement sequence for leads who cancel repeatedly." },
    ],
    relatedServices: ["virtual-assistance", "crm-support", "workflow-automation"],
  },
];

export function getServiceBySlug(slug: string): ServiceDetail | undefined {
  return SERVICE_DETAILS.find((s) => s.slug === slug);
}

export const SERVICE_SLUGS = SERVICE_DETAILS.map((s) => s.slug);
